packages:
  - '.'
  - 'docs'
  - 'config/*'
  - 'examples/*'
catalogs:
  dev:
    '@types/node': ^22.15.21
    '@types/react': ^19.1.5
    '@types/react-dom': ^19.1.5
    '@vitejs/plugin-react-swc': ^3.9.0
    react: ^19.1.0
    react-dom: ^19.1.0
    typescript: ^5.8.3
    vite: ^6.3.5